// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: teacher

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Pause_func(lv_event_t * e);
void Reset_func(lv_event_t * e);
void change_launch(lv_event_t * e);
void change_timer(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
